import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://safora.se/en/');
  await page.getByRole('link', { name: 'Contact Us' }).click();
  await page.getByRole('textbox', { name: 'Your Name' }).click();
  await page.getByRole('textbox', { name: 'Your Name' }).fill('Gayani Nadeeshani');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('gayaninadeeshani7@gmail.com');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('0757395769');
  await page.getByRole('textbox', { name: 'Your Message' }).click();
  await page.getByRole('textbox', { name: 'Your Message' }).fill('I\'m Gayani Nadeeshani. I\'m Interest of your company. I\'m looking for a intern. ');
  await page.locator('iframe[name="a-8rv0l2dmwgow"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-8rv0l2dmwgow"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Send Message' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Your Name' }).click();
  await page.getByRole('textbox', { name: 'Your Name' }).fill('hjhj');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('klklk');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('845');
  await page.getByRole('textbox', { name: 'Your Message' }).click();
  await page.getByRole('textbox', { name: 'Your Message' }).fill('kkk');
  await page.getByRole('button', { name: 'Send Message' }).click();
  await page.getByRole('textbox', { name: 'Your Name' }).click();
  await page.getByRole('textbox', { name: 'Your Name' }).fill('');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('');
  await page.getByRole('textbox', { name: 'Your Message' }).click();
  await page.getByRole('textbox', { name: 'Your Message' }).fill('');
  await page.getByRole('button', { name: 'Send Message' }).click();
  await page.getByRole('button', { name: 'Send Message' }).dblclick();
  await page.getByRole('button', { name: 'Send Message' }).dblclick();
  await page.getByRole('contentinfo').getByRole('link', { name: '+46 73 044 58' }).click();
  await page.getByRole('contentinfo').getByRole('link', { name: 'info@safora.se' }).click();
});